import type { ItemPage } from '@/types/item_types';

export const mockFetch = (): ItemPage => {
  return {
    metadata: {
      page: 1,
      perPage: 10,
      pageCount: 1,
      totalCount: 10,
      links: [
        {
          relation: 'self',
          url: 'http://localhost:3000/api/items?page=1&perPage=10',
        },
      ],
    },
    records: [
      {
        id: '1',
        description: 'A test item 1',
        price: 100,
        birthDay: new Date(),
        image: 'http://localhost:3000/api/items/1/image',
        gender: 'オス',
        breed: 'test breed 1',
        color: 'test color 1',
        weight: 1,
      },
      {
        id: '2',
        description: 'A test item 2',
        price: 200,
        birthDay: new Date(),
        image: 'http://localhost:3000/api/items/2/image',
        gender: 'メス',
        breed: 'test breed 2',
        color: 'test color 2',
        weight: 2,
      },
      {
        id: '3',
        description: 'A test item 3',
        price: 300,
        birthDay: new Date(),
        image: 'http://localhost:3000/api/items/3/image',
        gender: 'オス',
        breed: 'test breed 3',
        color: 'test color 3',
        weight: 3,
      },
      {
        id: '4',
        description: 'A test item 4',
        price: 400,
        birthDay: new Date(),
        image: 'http://localhost:3000/api/items/4/image',
        gender: 'メス',
        breed: 'test breed 4',
        color: 'test color 4',
        weight: 4,
      },
      {
        id: '5',
        description: 'A test item 5',
        price: 500,
        birthDay: new Date(),
        image: 'http://localhost:3000/api/items/5/image',
        gender: 'オス',
        breed: 'test breed 5',
        color: 'test color 5',
        weight: 5,
      },
      {
        id: '6',
        description: 'A test item 6',
        price: 600,
        birthDay: new Date(),
        image: 'http://localhost:3000/api/items/6/image',
        gender: 'メス',
        breed: 'test breed 6',
        color: 'test color 6',
        weight: 6,
      },
      {
        id: '7',
        description: 'A test item 7',
        price: 700,
        birthDay: new Date(),
        image: 'http://localhost:3000/api/items/7/image',
        gender: 'オス',
        breed: 'test breed 7',
        color: 'test color 7',
        weight: 7,
      },
      {
        id: '8',
        description: 'A test item 8',
        price: 800,
        birthDay: new Date(),
        image: 'http://localhost:3000/api/items/8/image',
        gender: 'メス',
        breed: 'test breed 8',
        color: 'test color 8',
        weight: 8,
      },
      {
        id: '9',
        description: 'A test item 9',
        price: 900,
        birthDay: new Date(),
        image: 'http://localhost:3000/api/items/9/image',
        gender: 'オス',
        breed: 'test breed 9',
        color: 'test color 9',
        weight: 9,
      },
      {
        id: '10',
        description: 'A test item 10',
        price: 1000,
        birthDay: new Date(),
        image: 'http://localhost:3000/api/items/10/image',
        gender: 'メス',
        breed: 'test breed 10',
        color: 'test color 10',
        weight: 10,
      },
    ],
  };
};
